/**
 *
 * @author Dominik Lorenc W65497
 */
public class V3nomterr extends javax.swing.JFrame {

    /**
     * Creates new form V3nomterr
     */
    public V3nomterr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        RadA1 = new javax.swing.JRadioButton();
        RadA2 = new javax.swing.JRadioButton();
        RadA3 = new javax.swing.JRadioButton();
        RadA4 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        RadA5 = new javax.swing.JRadioButton();
        RadA6 = new javax.swing.JRadioButton();
        RadA7 = new javax.swing.JRadioButton();
        RadA8 = new javax.swing.JRadioButton();
        RadA9 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        RadA10 = new javax.swing.JRadioButton();
        RadA11 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        Chk1 = new javax.swing.JCheckBox();
        Chk2 = new javax.swing.JCheckBox();
        Chk3 = new javax.swing.JCheckBox();
        CenaTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        BtnPods = new javax.swing.JButton();
        Btn2 = new javax.swing.JButton();
        Btn3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jSpinner5 = new javax.swing.JSpinner();
        jSpinner6 = new javax.swing.JSpinner();
        jSpinner7 = new javax.swing.JSpinner();
        jSpinner8 = new javax.swing.JSpinner();
        jSpinner9 = new javax.swing.JSpinner();
        jSpinner10 = new javax.swing.JSpinner();
        jSpinner11 = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jSpinner12 = new javax.swing.JSpinner();
        jSpinner13 = new javax.swing.JSpinner();
        jSpinner14 = new javax.swing.JSpinner();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 24)); // NOI18N
        jLabel1.setText("V3nomterr shop");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 0));
        jLabel2.setText("Dla początkujących:");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 0));
        jLabel3.setText("Dla średnio-zaawansowanych");

        jLabel4.setFont(new java.awt.Font("Yu Gothic Light", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Dla zaawansowanych ");

        RadA1.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        RadA1.setText("B.Boehemi L5 - 90 zł");
        RadA1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RadA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadA1ActionPerformed(evt);
            }
        });

        RadA2.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        RadA2.setText("B.Albiceps L7 - 100 zł");
        RadA2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RadA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadA2ActionPerformed(evt);
            }
        });

        RadA3.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        RadA3.setText("A.Geniculata L5 - 120 zł");
        RadA3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        RadA4.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        RadA4.setText("A.Geniculata L1 - 50 zł");
        RadA4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel5.setText("Ptaszniki :");

        RadA5.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        RadA5.setText("P.Irminia L3 - 90 zł");
        RadA5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RadA5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadA5ActionPerformed(evt);
            }
        });

        RadA6.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        RadA6.setText("N.Incei L8 - 120 zł");
        RadA6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        RadA7.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        RadA7.setText("D.Pentaloris L6 - 140 zł");
        RadA7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        RadA8.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        RadA8.setText("P.Metallica L5 - 280 zł");
        RadA8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RadA8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadA8ActionPerformed(evt);
            }
        });

        RadA9.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        RadA9.setText("P.Regalis L4 - 200 zł");
        RadA9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RadA9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadA9ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel6.setText("Akcesoria :");

        RadA10.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        RadA10.setText("Terrarium małe 15x15x10 - 50 zł");
        RadA10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        RadA11.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        RadA11.setText("Terrerium duże 35x35x20 - 120 zł");
        RadA11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setFont(new java.awt.Font("Yu Gothic Light", 0, 14)); // NOI18N
        jLabel8.setText("Czy dodać do zamówienia żywą karmówkę?");

        Chk1.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        Chk1.setText("Tak, karaczan turecki 20 szt. - 20 zł");
        Chk1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Chk2.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        Chk2.setText("Tak, świerszcz kubański 20 szt. - 15 zł");
        Chk2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Chk3.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        Chk3.setText("Tak, larwy mącznika 20 szt. - 10 zł");
        Chk3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        CenaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CenaTxtActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 2, 14)); // NOI18N
        jLabel7.setText("Łączna cena : ");

        BtnPods.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        BtnPods.setText("Podsumowanie");
        BtnPods.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnPods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPodsActionPerformed(evt);
            }
        });

        Btn2.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        Btn2.setText("Wyczyść");
        Btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn2ActionPerformed(evt);
            }
        });

        Btn3.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        Btn3.setText("Wyjdź");
        Btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn3ActionPerformed(evt);
            }
        });

        jButton1.setText("Quiz :)");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));
        jSpinner1.setMaximumSize(new java.awt.Dimension(3213, 3213));

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        jSpinner4.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        jSpinner5.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        jSpinner6.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        jSpinner7.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        jSpinner8.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        jSpinner9.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        jSpinner10.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));

        jSpinner11.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jLabel9.setText("( 1 opakowanie = 20 szt)");

        jSpinner12.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        jSpinner12.setMaximumSize(new java.awt.Dimension(32767, 3267));

        jSpinner13.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));

        jSpinner14.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(11, 11, 11)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addComponent(RadA10)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(jSpinner10, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(50, 50, 50))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(RadA11)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(jSpinner11)
                                                                                .addGap(39, 39, 39))))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(Btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(215, 215, 215)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(Chk1)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                        .addGap(6, 6, 6)
                                                                        .addComponent(jLabel7)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(CenaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addComponent(Chk2)
                                                                .addComponent(jLabel8))
                                                        .addComponent(Chk3))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel9)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jSpinner14, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jSpinner13, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jSpinner12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addGap(48, 48, 48)))
                                                .addGap(156, 156, 156))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(11, 11, 11)
                                                                .addComponent(jLabel5))
                                                        .addComponent(jLabel2)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(46, 46, 46)
                                                                .addComponent(jLabel6))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(RadA1)
                                                                        .addComponent(RadA2))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jSpinner2)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(RadA3)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(56, 56, 56)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(RadA5)
                                                                        .addComponent(RadA6))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(164, 164, 164)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(RadA9)
                                                                        .addComponent(RadA8)))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jLabel3)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                                .addComponent(RadA7)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jSpinner7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(157, 157, 157)
                                                                .addComponent(jLabel4)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jSpinner8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jSpinner9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(39, 39, 39))))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(317, 317, 317)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(RadA4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(BtnPods)
                                        .addComponent(Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(304, 304, 304)
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel5)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel4)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(RadA1)
                                                        .addComponent(RadA5)
                                                        .addComponent(RadA8)
                                                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jSpinner8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(jSpinner2))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(RadA2)
                                                                .addComponent(RadA6)
                                                                .addComponent(RadA9)
                                                                .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jSpinner9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(RadA7)
                                                        .addComponent(RadA3)
                                                        .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jSpinner7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(RadA4)
                                                        .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(53, 53, 53)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel8)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel9))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(Chk1)
                                                        .addComponent(jSpinner12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(RadA10)
                                                .addComponent(jSpinner10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jSpinner11))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(Chk2)
                                                .addComponent(RadA11)
                                                .addComponent(jSpinner13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Chk3)
                                        .addComponent(jSpinner14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(BtnPods)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(76, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(jButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(CenaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel7)
                                                        .addComponent(Btn3))
                                                .addGap(39, 39, 39))))
        );

        jSpinner2.getAccessibleContext().setAccessibleName("");
        jSpinner2.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>

    private void RadA1ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void RadA2ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void RadA5ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void RadA9ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void CenaTxtActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void BtnPodsActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        double Łącznie = 0;

        if(RadA1.isSelected()){
            Łącznie = Łącznie + (90 * Integer.parseInt(jSpinner1.getValue().toString()));
        }if(RadA2.isSelected()) {
            Łącznie = Łącznie +(100 * Integer.parseInt(jSpinner2.getValue().toString()));
        }if(RadA3.isSelected()) {
            Łącznie = Łącznie + (120 * Integer.parseInt(jSpinner3.getValue().toString()));
        }if(RadA4.isSelected()) {
            Łącznie = Łącznie + (50 * Integer.parseInt(jSpinner4.getValue().toString()));
        }if(RadA5.isSelected()) {
            Łącznie = Łącznie +  ( 90 * Integer.parseInt(jSpinner5.getValue().toString()));
        }
        if(RadA6.isSelected()) {
            Łącznie = Łącznie + (120 * Integer.parseInt(jSpinner6.getValue().toString()));
        } if(RadA7.isSelected()) {
            Łącznie = Łącznie + (140 * Integer.parseInt(jSpinner7.getValue().toString()));
        } if(RadA8.isSelected()) {
            Łącznie = Łącznie + (280 * Integer.parseInt(jSpinner8.getValue().toString()));
        } if(RadA9.isSelected()) {
            Łącznie = Łącznie + (200 * Integer.parseInt(jSpinner9.getValue().toString()));
        } if(RadA10.isSelected()) {
            Łącznie = Łącznie + (50 * Integer.parseInt(jSpinner10.getValue().toString()));
        } if(RadA11.isSelected()) {
            Łącznie = Łącznie + (120 * Integer.parseInt(jSpinner11.getValue().toString()));
        }

        if(Chk1.isSelected()) {
            Łącznie = Łącznie + (20 * Integer.parseInt(jSpinner12.getValue().toString()));
        }if(Chk2.isSelected()) {
            Łącznie = Łącznie + (15 * Integer.parseInt(jSpinner13.getValue().toString()));
        }if(Chk3.isSelected()) {
            Łącznie = Łącznie + (10 * Integer.parseInt(jSpinner14.getValue().toString()));
        }
        CenaTxt.setText(Double.toString(Łącznie));

    }

    private void Btn3ActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }

    private void Btn2ActionPerformed(java.awt.event.ActionEvent evt) {
        RadA1.setSelected(false);
        RadA2.setSelected(false);
        RadA3.setSelected(false);
        RadA4.setSelected(false);
        RadA5.setSelected(false);
        RadA6.setSelected(false);
        RadA7.setSelected(false);
        RadA8.setSelected(false);
        RadA9.setSelected(false);
        RadA10.setSelected(false);
        Chk1.setSelected(false);
        Chk2.setSelected(false);
        Chk3.setSelected(false);
        RadA11.setSelected(false);
        CenaTxt.setText("");
        jSpinner1.setValue(0);
        jSpinner2.setValue(0);
        jSpinner3.setValue(0);
        jSpinner4.setValue(0);
        jSpinner5.setValue(0);
        jSpinner6.setValue(0);
        jSpinner7.setValue(0);
        jSpinner8.setValue(0);
        jSpinner9.setValue(0);
        jSpinner10.setValue(0);
        jSpinner11.setValue(0);
        jSpinner12.setValue(0);
        jSpinner13.setValue(0);
        jSpinner14.setValue(0);

    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        Quiz quiz = new Quiz();
        quiz.jButton1ActionPerformed(evt);
    }

    private void RadA8ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V3nomterr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V3nomterr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V3nomterr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V3nomterr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V3nomterr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton Btn2;
    private javax.swing.JButton Btn3;
    private javax.swing.JButton BtnPods;
    private javax.swing.JTextField CenaTxt;
    private javax.swing.JCheckBox Chk1;
    private javax.swing.JCheckBox Chk2;
    private javax.swing.JCheckBox Chk3;
    private javax.swing.JRadioButton RadA1;
    private javax.swing.JRadioButton RadA10;
    private javax.swing.JRadioButton RadA11;
    private javax.swing.JRadioButton RadA2;
    private javax.swing.JRadioButton RadA3;
    private javax.swing.JRadioButton RadA4;
    private javax.swing.JRadioButton RadA5;
    private javax.swing.JRadioButton RadA6;
    private javax.swing.JRadioButton RadA7;
    private javax.swing.JRadioButton RadA8;
    private javax.swing.JRadioButton RadA9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner10;
    private javax.swing.JSpinner jSpinner11;
    private javax.swing.JSpinner jSpinner12;
    private javax.swing.JSpinner jSpinner13;
    private javax.swing.JSpinner jSpinner14;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JSpinner jSpinner8;
    private javax.swing.JSpinner jSpinner9;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration
}
